// Generated by CoffeeScript 2.7.0
(function() {
  var buttonBlock, sum;

  buttonBlock = document.querySelector('.button');

  sum = 0;

  buttonBlock.addEventListener('click', function() {
    sum += 1;
    return buttonBlock.textContent = sum;
  });

}).call(this);
