/* eslint-disable no-unused-vars */
// Generated by CoffeeScript 2.7.0
// eslint-disable-next-line func-names
(function () {
  let cube; let
    square;

  // eslint-disable-next-line prefer-const, func-names
  square = function (x) {
    return x * x;
  };

  // eslint-disable-next-line prefer-const, func-names
  cube = function (x) {
    return square(x) * x;
  };
}).call(this);
